### ISSUE TITLE
The service 'App\Http\Controllers\CampaignService' is not available. Please pass a valid service

### ISSUE THREAD

**Issue by hichamuim** [Edujugon/laravel-google-ads#4]
Hello,

$ads = new GoogleAds();
$ads->service(CampaignService::class);

I Get This Error 

`

> The service 'App\Http\Controllers\CampaignService' is not available. Please pass a valid service

`

**Comment by Edujugon** [comment]
Hi @hichamuim 
You should add the use statement at the top of your file for the CampaignService.

That services is in google namespace. Now your code is trying to take that serve from the same folder as your controller is.

**Comment by Edujugon** [comment]
@hichamuim ,

try to add this at the top of your class:

```php
namespace Google\AdsApi\AdWords\v201708\cm;
```

**Comment by hichamuim** [comment]
Hi @Edujugon ,

The error is resolved when i add  # **use CampaignService;**

But i hyave another error 

> The service 'CampaignService' is not available. Please pass a valid service

**Comment by Edujugon** [comment]
Hi @hichamuim ,

remove that use statement and add this one:

```php
use Google\AdsApi\AdWords\v201708\cm\CampaignService;
```

**Comment by hichamuim** [comment]
it works, thank you @Edujugon 👍

**Comment by DzinPerformmaOnline** [comment]
Hi @Edujugon,
I got the same error as @hichamuim, but when I add the use statement as you said it still returns this error:
The service 'Google\AdsApi\AdWords\v201708\cm\CampaignService' is not available. Please pass a valid service

Can you help me?

**Comment by kunalm7865** [comment]
@Edujugon i am still facing issue after adding this :- 
use Google\AdsApi\AdWords\v201708\cm\CampaignService;

![Screenshot from 2020-06-07 22-44-13](https://user-images.githubusercontent.com/66566648/83975229-72464480-a910-11ea-8f63-4a929ac08c3c.png)
